server:
  port: 8889
  compression:
    enabled: true

zuul:
  routes:
    api:
      path: /video_proxy/**
      url: http://www.google.como
  ssl-hostname-validation-enabled: false
  host:
    socket-timeout-millis: 30000

logging:
  level:
    root: info
  file:
    name: /tmp/video_proxy.log
